name: viajes
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  awesome_dialog: ^3.2.0
  carousel_slider: ^4.2.1
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_native_splash: 2.3.10
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.0.0
  flutter_slidable: ^3.0.1
  get: ^4.6.6
  go_router: ^13.2.0
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  intl: ^0.19.0
  jwt_decode: ^0.3.1
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/
    - assets/images/content/
    - assets/images/banners/
    - assets/images/reviews/
    - assets/images/products/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/icons/payment_methods/
    - assets/images/on_boarding_images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
